#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUT                               100
#define IDM_EXIT                                100
#define IDI_MAINICON                            101
#define IDM_ABOUT                               101
#define IDM_ADD_ITEM                            102
#define IDM_MAIN_MENU                           102
#define IDM_CONTEXT_MENU                        103
#define IDM_REMOVE_ITEM                         103
#define IDI_DISK                                104
#define ID_SOUND_PLAY                           104
#define IDD_ADD_ITEM                            105
#define ID_SOUND_PAUSE                          105
#define IDD_REMOVE_ITEM                         106
#define ID_SOUND_STOP                           106
#define IDI_BRICK                               107
#define ID_ENTRIES_SENDDATA                     107
#define IDI_NGCH                                108
#define ID_SOUND_STARTRECEIVER                  108
#define ID_SOUND_STOPRECEIVER                   109
#define ID_ENTRIES_STOPSENDER                   111
#define IDR_MENU1                               113
#define IDD_MAIN_SENDER                         114
#define IDD_MAIN_RECEIVER                       116
#define IDR_MENU2                               117
#define IDR_0_1                                 118
#define IDR_0_2                                 119
#define IDD_DIALOG1                             120
#define IDM_LARGE_ICONS                         200
#define IDM_SMALL_ICONS                         201
#define IDM_LIST                                202
#define IDM_JOIN_MCAST                          203
#define IDM_REPORT                              204
#define IDM_SETUP_MCAST                         205
#define IDC_RECEIVER_BUFFER                     1001
#define IDC_BRICK                               1002
#define IDC_CONTROL_HEAD                        1003
#define IDC_ID                                  1005
#define IDC_TEI                                 1006
#define ID_RECEIVER_SETTINGS                    1007
#define IDS_APPTITLE_SENDER                     40000
#define ID_RECEIVER_STARTRCV                    40000
#define ID_SENDER_LEAVEMCAST                    40000
#define IDS_APPTITLE_RECEIVER                   40001
#define ID_RECEIVER_STOPRCV                     40001
#define ID_SENDER_SETTINGS                      40001
#define IDT_TIMER_1                             40002
#define IDS_APPTITLE                            40003
#define ID_SENDER_JOINMCAST                     40008
#define ID_SENDER_STARTSENDING                  40009
#define ID_SENDER_STOPSENDING                   40010
#define ID_RECEIVER_JOINMCAST                   40011
#define ID_RECEIVER_LEAVEMCAST                  40012
#define ID_RECEIVER_PLAY                        40015
#define ID_RECEIVER_STOP                        40016
